### ISSUE TITLE
Example project

### ISSUE THREAD

**Issue by neoneye** [hallee/neumorphic-style#1]
Your `NeumorphicButtonStyle` looks awesome, and your blog post is nice.

An example project would be nice. Maybe as a separate repository.

So that different configurations can be seen right away.

Really cool project you have here.

**Comment by hallee** [comment]
Thanks for the feedback. I think the [Swift Playground](https://s3.amazonaws.com/f.hal.codes/SwiftUI+Neumorphism.playgroundbook.zip) serves this function well.
